# Generated by Django 4.1.7 on 2023-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=128)),
                ("position", models.CharField(max_length=128)),
                ("subjects", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile/"),
                ),
            ],
        ),
    ]
